# Расширения реализация включающая oneOf, anyOf, allOf, not
# todo В данный момент тут описаны но не задействованы все схемы. Незадействованные помечены "todo"
# todo Нужно сделать JSON файл на основе данного yaml и использовать его в тестах

openapi: 3.0.0
info:
  title: Demo API
  version: 1.0.0
  description: Demo API with various OpenAPI features

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [admin, user, guest]
        tags:
          type: array
          items:
            type: string
        metadata:
          type: object
          additionalProperties:
            type: string
        birthDate:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        score:
          type: number
          format: float
          minimum: 0
          maximum: 100
        isActive:
          type: boolean
          default: true

    # Пример использования oneOf # todo не используются
    UserResponse:
      oneOf:
        - $ref: '#/components/schemas/User'
        - $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          user: '#/components/schemas/User'
          error: '#/components/schemas/Error'

    # Пример использования anyOf # todo не используются
    SearchFilter:
      type: object
      anyOf:
        - type: object
          properties:
            name:
              type: string
            minScore:
              type: number
          required: [ name ]
        - type: object
          properties:
            role:
              type: string
            isActive:
              type: boolean
          required: [ role ]
        - type: object
          properties:
            dateRange:
              type: object
              properties:
                start:
                  type: string
                  format: date
                end:
                  type: string
                  format: date
              required: [ start, end ]

    # Пример использования allOf # todo не используются
    AdminUser:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            adminLevel:
              type: integer
              minimum: 1
              maximum: 5
            permissions:
              type: array
              items:
                type: string
          required:
            - adminLevel
            - permissions

    # Пример использования not # todo не используются
    NonAdminUser:
      not:
        type: object
        properties:
          role:
            type: string
            enum: [admin]
        required: [role]

    # Комбинированный пример # todo не используются
    ComplexUserValidation:
      allOf:
        - $ref: '#/components/schemas/User'
        - anyOf:
            - type: object
              properties:
                verificationStatus:
                  type: string
                  enum: [verified, pending]
            - type: object
              properties:
                externalIds:
                  type: array
                  items:
                    type: string
        - not:
            type: object
            properties:
              role:
                type: string
                enum: [blocked, deleted]

    # Пример вложенного использования # todo не используются
    UserGroupMembership:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        groupType:
          oneOf:
            - type: object
              properties:
                department:
                  type: string
                level:
                  type: integer
              required: [department]
            - type: object
              properties:
                projectId:
                  type: string
                role:
                  type: string
              required: [projectId]
        access:
          allOf:
            - type: object
              properties:
                level:
                  type: string
                  enum: [read, write, admin]
            - type: object
              properties:
                expiresAt:
                  type: string
                  format: date-time

    # Пример с дискриминатором # todo не используются
    PetResponse:
      oneOf:
        - type: object
          properties:
            petType:
              type: string
              enum: [dog]
            breed:
              type: string
            bark:
              type: string
          required: [petType, breed]
        - type: object
          properties:
            petType:
              type: string
              enum: [cat]
            breed:
              type: string
            meow:
              type: string
          required: [petType, breed]
      discriminator:
        propertyName: petType
        mapping:
          dog: '#/components/schemas/DogPet'
          cat: '#/components/schemas/CatPet'

  parameters:
    IdInPath:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64

    PageQuery:
      name: page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1

    AuthHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        pattern: '^Bearer \w+$'

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /users:
    get:
      summary: List users
      parameters:
        - $ref: '#/components/parameters/PageQuery'
        - $ref: '#/components/parameters/AuthHeader'
        - name: role
          in: query
          schema:
            type: string
            enum: [admin, user, guest]
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create user
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                role:
                  type: string
                  enum: [user, guest]
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/IdInPath'

    get:
      summary: Get user by ID
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update user
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Partially update user
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                role:
                  type: string
                  enum: [admin, user, guest]
      responses:
        '200':
          description: User partially updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete user
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      responses:
        '204':
          description: User deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /users/batch:
    post:
      summary: Batch create users
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                users:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Users created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'