import { OpenAPIV3 } from 'openapi-types';
import { ParametersMap } from '../utils/parametersToMap/parametersToMap.types';

/**
 * Contain *OpenAPI* and *Arc* fields.
 * - *OpenAPI* fields - native fields from OpenAPI yaml/json document.
 * - *Arc* fields - field prepared for code generator.
 * */
export type Method = {
  /**
   * OpenAPI field.
   * @example GET, POST, PUT, DELETE, etc */
  method: OpenAPIV3.HttpMethods;

  /**
   * OpenAPI field.
   * @example 'users/:id' */
  path: string;

  /**
   * OpenAPI field.
   * Description from openAPI document */
  description: string;

  /**
   * OpenAPI field.
   * Summary from openAPI document */
  summary: string;

  /**
   * OpenAPI field.
   * Tags from openAPI document */
  tags: string[];

  /**
   * Arc field.
   * {@link ParametersMap} */
  parametersMap: ParametersMap;

  /**
   * Arc field.
   * Typescript type generated by scheme of success status or "default"
   * - 200 || 201 || default
   * - "application/json" || "multipart/form-data" || "application/x-www-form-urlencoded"
   * */
  responseType: string;

  /**
   * Arc field.
   * Typescript type generated by scheme of [path][method].requestBody
   * */
  requestBodyType: string;

  /**
   * Arc field.
   * Generated method name by OpenAPI path. Generated by function "methodNameByPath()"
   * @example
   * '/users/{id}' > 'usersById'
   * */
  generatedMethodName: string;

  /**
   * Arc field.
   * Generated method for get endpoint url.
   *
   * @example
   * export const getUsersById = ({ userId }) => `/users/${userId}`
   * */
  urlGetter: string;
};
